import type { SearchEntry } from "@/app/_lib/search-types"

// Static pages and top-level routes that are not CMS-driven.
// CMS pages (/adopt/[slug], /volunteer/[slug], /donate/[slug]) and events
// are merged in at request time by buildSearchManifest.
export const staticSearchEntries: SearchEntry[] = [
    {
        id: "page-home",
        title: "Home",
        description: "Greyhound Pets of America — Minnesota",
        href: "/",
        category: "Pages",
    },
    {
        id: "page-adopt",
        title: "Adopt",
        description: "Learn about adopting a retired racing greyhound.",
        href: "/adopt",
        category: "Pages",
    },
    {
        id: "page-adopt-available",
        title: "Available Dogs",
        description: "Greyhounds currently available for adoption.",
        href: "/adopt/available",
        category: "Pages",
        keywords: ["dogs", "available", "hounds", "meet"],
    },
    {
        id: "page-adopt-process",
        title: "Our Adoption Process",
        description: "Step-by-step guide to adopting from GPA-MN.",
        href: "/adopt/our-process",
        category: "Pages",
        keywords: ["process", "application", "how to adopt"],
    },
    {
        id: "page-adopt-support",
        title: "Post-Adoption Support",
        description: "Resources for new greyhound adopters.",
        href: "/adopt/support",
        category: "Pages",
        keywords: ["support", "help", "after adoption"],
    },
    {
        id: "page-adopt-why",
        title: "Why GPA-MN?",
        description: "What sets our adoption program apart.",
        href: "/adopt/why-gpa-mn",
        category: "Pages",
    },
    {
        id: "page-volunteer",
        title: "Volunteer",
        description: "Ways to get involved with GPA-MN.",
        href: "/volunteer",
        category: "Pages",
        keywords: ["help", "get involved"],
    },
    {
        id: "page-donate",
        title: "Donate",
        description: "Support our greyhound adoption mission.",
        href: "/donate",
        category: "Pages",
        keywords: ["give", "contribute", "support"],
    },
    {
        id: "page-events",
        title: "Events",
        description: "Upcoming GPA-MN events, walks, and meet-and-greets.",
        href: "/events",
        category: "Pages",
    },
    {
        id: "page-about",
        title: "About",
        description: "About Greyhound Pets of America — Minnesota.",
        href: "/about",
        category: "Pages",
    },
    {
        id: "page-contact",
        title: "Contact",
        description: "Get in touch with GPA-MN.",
        href: "/about/contact",
        category: "Pages",
        keywords: ["email", "phone", "reach out"],
    },
    {
        id: "page-lost-hound",
        title: "Lost Hound!",
        description: "What to do if you've lost your greyhound.",
        href: "/lost-hound",
        category: "Pages",
        keywords: ["missing", "runaway", "escaped"],
    },
    {
        id: "page-apply-adopt",
        title: "Adoption Application",
        description: "Apply to adopt a greyhound.",
        href: "/adopt/apply",
        category: "Pages",
        keywords: ["application", "apply", "form"],
    },
    {
        id: "page-apply-foster",
        title: "Foster Application",
        description: "Apply to foster a greyhound.",
        href: "/foster/apply",
        category: "Pages",
        keywords: ["foster", "application", "apply"],
    },
]
